import { addDays } from "date-fns";

export const categories = [
  {
    id: "desk-chaos",
    name: "Desk Chaos",
    slug: "desk-chaos",
    image: "https://picsum.photos/seed/desk-chaos/800/600",
    description: "Office upgrades with zero chill.",
  },
  {
    id: "kitchen-madness",
    name: "Kitchen Madness",
    slug: "kitchen-madness",
    image: "https://picsum.photos/seed/kitchen-madness/800/600",
    description: "Cooking tools with dramatic personality.",
  },
  {
    id: "gift-a-wtf",
    name: "Gift a WTF",
    slug: "gift-a-wtf",
    image: "https://picsum.photos/seed/gift-a-wtf/800/600",
    description: "Ridiculous gifts people never forget.",
  },
  {
    id: "wearable-weirdness",
    name: "Wearable Weirdness",
    slug: "wearable-weirdness",
    image: "https://picsum.photos/seed/wearable-weirdness/800/600",
    description: "Fashion choices that demand attention.",
  },
  {
    id: "tech-oddities",
    name: "Tech Oddities",
    slug: "tech-oddities",
    image: "https://picsum.photos/seed/tech-oddities/800/600",
    description: "Gadgets from an alternate timeline.",
  },
  {
    id: "prank-central",
    name: "Prank Central",
    slug: "prank-central",
    image: "https://picsum.photos/seed/prank-central/800/600",
    description: "Harmless chaos for certified troublemakers.",
  },
];

export const products = [
  {
    id: "prod-1",
    slug: "screaming-goat-coffee-mug",
    name: "Screaming Goat Coffee Mug",
    shortDescription: "Press the handle and your goat screams into Monday.",
    description:
      "A ceramic mug with a tiny sound module that lets out a dramatic goat scream when squeezed. Dishwasher-safe top, battery compartment in the base, and guaranteed desk-side conversation starter.",
    price: 799,
    compareAtPrice: 1199,
    sku: "ODF-MUG-GOAT-01",
    images: [
      "https://picsum.photos/seed/screaming-goat-1/1000/1000",
      "https://picsum.photos/seed/screaming-goat-2/1000/1000",
    ],
    category: "kitchen-madness",
    rating: 4.7,
    reviewCount: 132,
    tags: ["trending", "gift", "office"],
    inventory: 7,
    lowStockThreshold: 10,
    fakeViewers: 22,
    sold24h: 18,
    isFeatured: true,
    isNew: false,
    weight: 450,
    dimensions: { length: 10, width: 8, height: 11 },
  },
  {
    id: "prod-2",
    slug: "usb-pet-rock",
    name: "USB Pet Rock",
    shortDescription: "Charges nothing. Judges everything.",
    description:
      "A perfectly smooth desk stone with a fake USB-C port and tiny status LED. It does absolutely nothing except improve your vibe and confuse coworkers.",
    price: 499,
    compareAtPrice: 899,
    sku: "ODF-TECH-ROCK-01",
    images: [
      "https://picsum.photos/seed/usb-rock-1/1000/1000",
      "https://picsum.photos/seed/usb-rock-2/1000/1000",
    ],
    category: "tech-oddities",
    rating: 4.4,
    reviewCount: 88,
    tags: ["tech", "desk", "viral"],
    inventory: 52,
    lowStockThreshold: 8,
    fakeViewers: 14,
    sold24h: 9,
    isFeatured: true,
    isNew: true,
    weight: 180,
    dimensions: { length: 7, width: 5, height: 4 },
  },
  {
    id: "prod-3",
    slug: "pizza-socks-box",
    name: "Pizza Socks Box",
    shortDescription: "Pepperoni look, cozy feel.",
    description:
      "Four rolled-up sock pairs packed like a pizza pie. Soft combed cotton blend, one-size comfort, and chaotic gifting guaranteed.",
    price: 999,
    compareAtPrice: 1499,
    sku: "ODF-WEAR-PIZZA-01",
    images: [
      "https://picsum.photos/seed/pizza-socks-1/1000/1000",
      "https://picsum.photos/seed/pizza-socks-2/1000/1000",
    ],
    category: "wearable-weirdness",
    rating: 4.8,
    reviewCount: 210,
    tags: ["gift", "wearable", "new"],
    inventory: 24,
    lowStockThreshold: 6,
    fakeViewers: 31,
    sold24h: 27,
    isFeatured: true,
    isNew: true,
    weight: 260,
    dimensions: { length: 22, width: 22, height: 4 },
  },
  {
    id: "prod-4",
    slug: "portable-clouds-night-light",
    name: "Portable Clouds Night Light",
    shortDescription: "Mini cloud on your desk with ambient glow.",
    description:
      "Rechargeable bedside cloud lamp with soft-touch silicone and three brightness levels. Looks dreamy, travels easy, and won’t leak weather.",
    price: 1399,
    compareAtPrice: 2199,
    sku: "ODF-TECH-CLOUD-01",
    images: [
      "https://picsum.photos/seed/cloud-light-1/1000/1000",
      "https://picsum.photos/seed/cloud-light-2/1000/1000",
    ],
    category: "tech-oddities",
    rating: 4.6,
    reviewCount: 156,
    tags: ["light", "home", "viral"],
    inventory: 5,
    lowStockThreshold: 10,
    fakeViewers: 19,
    sold24h: 16,
    isFeatured: true,
    isNew: false,
    weight: 320,
    dimensions: { length: 14, width: 10, height: 9 },
  },
  {
    id: "prod-5",
    slug: "dramatic-chipmunk-desk-toy",
    name: "Dramatic Chipmunk Desk Toy",
    shortDescription: "Turns with maximum side-eye energy.",
    description:
      "A spring-mounted desk figurine inspired by the internet's most dramatic stare. Tap it for instant emotional support during meetings.",
    price: 649,
    compareAtPrice: 999,
    sku: "ODF-DESK-CHIP-01",
    images: [
      "https://picsum.photos/seed/chipmunk-toy-1/1000/1000",
      "https://picsum.photos/seed/chipmunk-toy-2/1000/1000",
    ],
    category: "desk-chaos",
    rating: 4.3,
    reviewCount: 74,
    tags: ["desk", "toy", "meme"],
    inventory: 40,
    lowStockThreshold: 5,
    fakeViewers: 9,
    sold24h: 11,
    isFeatured: false,
    isNew: true,
    weight: 210,
    dimensions: { length: 12, width: 9, height: 14 },
  },
  {
    id: "prod-6",
    slug: "emotional-support-pickle",
    name: "Emotional Support Pickle",
    shortDescription: "A tiny plush pickle with big emotional range.",
    description:
      "Pocket-sized plush pickle with stitched face options and removable quote tags. Soft, absurd, and shockingly comforting.",
    price: 349,
    compareAtPrice: 599,
    sku: "ODF-GIFT-PICKLE-01",
    images: [
      "https://picsum.photos/seed/pickle-1/1000/1000",
      "https://picsum.photos/seed/pickle-2/1000/1000",
    ],
    category: "gift-a-wtf",
    rating: 4.9,
    reviewCount: 321,
    tags: ["gift", "plush", "viral"],
    inventory: 68,
    lowStockThreshold: 10,
    fakeViewers: 45,
    sold24h: 34,
    isFeatured: true,
    isNew: false,
    weight: 90,
    dimensions: { length: 12, width: 4, height: 4 },
  },
  {
    id: "prod-7",
    slug: "mood-ring-water-bottle",
    name: "Mood Ring Water Bottle",
    shortDescription: "Hydration with dramatic color-shift vibes.",
    description:
      "Double-wall stainless bottle with thermo-sensitive wrap that changes color with temperature and hand warmth.",
    price: 899,
    compareAtPrice: 1399,
    sku: "ODF-KITCHEN-MOOD-01",
    images: [
      "https://picsum.photos/seed/mood-bottle-1/1000/1000",
      "https://picsum.photos/seed/mood-bottle-2/1000/1000",
    ],
    category: "kitchen-madness",
    rating: 4.5,
    reviewCount: 98,
    tags: ["kitchen", "hydration", "new"],
    inventory: 15,
    lowStockThreshold: 8,
    fakeViewers: 16,
    sold24h: 13,
    isFeatured: false,
    isNew: true,
    weight: 330,
    dimensions: { length: 8, width: 8, height: 27 },
  },
  {
    id: "prod-8",
    slug: "invisible-ink-prank-pen-set",
    name: "Invisible Ink Prank Pen Set",
    shortDescription: "Write secrets. Reveal with UV. Start drama.",
    description:
      "Set of five invisible-ink pens and one UV keylight. Great for scavenger hunts, bad jokes, and sibling-level espionage.",
    price: 299,
    compareAtPrice: 499,
    sku: "ODF-PRANK-INK-01",
    images: [
      "https://picsum.photos/seed/ink-prank-1/1000/1000",
      "https://picsum.photos/seed/ink-prank-2/1000/1000",
    ],
    category: "prank-central",
    rating: 4.1,
    reviewCount: 64,
    tags: ["prank", "kids", "party"],
    inventory: 90,
    lowStockThreshold: 12,
    fakeViewers: 6,
    sold24h: 8,
    isFeatured: false,
    isNew: false,
    weight: 120,
    dimensions: { length: 15, width: 10, height: 2 },
  },
];

export const reviews = [
  {
    id: "rev-1",
    productId: "prod-1",
    rating: 5,
    title: "Mug changed my office reputation",
    body: "Now people come to my desk just to hear the goat scream. Quality is actually solid too.",
    authorName: "Aarav S.",
    authorLocation: "Delhi",
    isVerified: true,
    helpfulCount: 19,
    createdAt: addDays(new Date(), -3).toISOString(),
  },
  {
    id: "rev-2",
    productId: "prod-6",
    rating: 5,
    title: "Pickle has range",
    body: "I bought this as a joke and now it lives in my laptop bag. Unexpected emotional support item.",
    authorName: "Meera P.",
    authorLocation: "Mumbai",
    isVerified: true,
    helpfulCount: 28,
    createdAt: addDays(new Date(), -6).toISOString(),
  },
  {
    id: "rev-3",
    productId: "prod-4",
    rating: 4,
    title: "Very cute bedside light",
    body: "Soft glow is perfect. Battery could be a little better but still worth it.",
    authorName: "Rohan K.",
    authorLocation: "Pune",
    isVerified: false,
    helpfulCount: 8,
    createdAt: addDays(new Date(), -8).toISOString(),
  },
];

export const deals = [
  {
    id: "deal-1",
    productSlug: "portable-clouds-night-light",
    dealEndsAt: addDays(new Date(), 1).toISOString(),
    claimedPercent: 73,
  },
  {
    id: "deal-2",
    productSlug: "pizza-socks-box",
    dealEndsAt: addDays(new Date(), 2).toISOString(),
    claimedPercent: 61,
  },
];

export const orderStatuses = [
  "PENDING",
  "CONFIRMED",
  "PROCESSING",
  "SHIPPED",
  "OUT_FOR_DELIVERY",
  "DELIVERED",
  "CANCELLED",
];

export const shippingZones = [
  { zone: "India", baseRate: 79, days: "2-5" },
  { zone: "South Asia", baseRate: 399, days: "5-8" },
  { zone: "Southeast Asia", baseRate: 549, days: "6-10" },
  { zone: "Middle East", baseRate: 699, days: "7-12" },
  { zone: "Europe", baseRate: 899, days: "8-14" },
  { zone: "North America", baseRate: 999, days: "8-14" },
  { zone: "Rest of World", baseRate: 1199, days: "10-18" },
];

export const aiAgents = [
  "Review Generator",
  "Product Finder",
  "Negotiation Drafter",
  "Description Writer",
  "Cost Calculator",
  "Smart Pricing",
  "Customer Service Bot (TODO)",
  "Inventory Optimizer (TODO)",
  "SEO Content Writer (TODO)",
  "Ad Copy Generator (TODO)",
  "Supplier Auto-Discovery (TODO)",
];
